const ERROR_MAP: Record<string, string> = {
  "Manual price override reason is required": "سبب تعديل السعر مطلوب.",
  "Manual compensation override reason is required": "سبب تعديل تعويض الأستاذ مطلوب.",
  "One or more students were not found": "تعذر العثور على أحد الطلاب.",
  "Inactive or archived students cannot be assigned without permission": "لا يمكن إسناد الحصة لطالب غير نشط أو مؤرشف دون صلاحية.",
  "Teacher is inactive, unavailable, suspended, or resigned": "الأستاذ غير متاح أو غير نشط أو موقوف أو مستقيل.",
  teacher_inactive: "الأستاذ غير نشط.",
  teacher_on_leave: "الأستاذ في عطلة.",
  teacher_suspended: "الأستاذ موقوف.",
  teacher_resigned: "الأستاذ مستقيل.",
  teacher_conflict: "الأستاذ لديه حصة أخرى في هذا التوقيت.",
  student_conflict: "الطالب لديه حصة أخرى في هذا التوقيت.",
  "Teacher is not assigned to this subject": "الأستاذ غير مكلّف بهذه المادة.",
  "Teacher is not assigned to this academic level": "الأستاذ غير مكلّف بهذا المستوى.",
  "Teacher has an overlapping private lesson": "الأستاذ لديه حصة أخرى في هذا التوقيت.",
  "A selected student has an overlapping private lesson": "الطالب لديه حصة أخرى في هذا التوقيت.",
  "Room has an overlapping private lesson": "القاعة لديها حجز آخر في هذا التوقيت.",
  "Teacher weekly schedule conflicts with this lesson": "الأستاذ لديه حصة أخرى في هذا التوقيت.",
  "Existing course schedule conflicts with this lesson": "يوجد برنامج دورة متداخل مع هذا التوقيت.",
  "Invalid lesson id": "معرّف الحصة غير صالح.",
  "Private lesson not found": "الحصة الخاصة غير موجودة.",
  "Teacher is required": "الأستاذ مطلوب.",
  "At least one student is required": "يجب اختيار طالب واحد على الأقل.",
  "Duplicate students are not allowed in the same lesson": "لا يمكن تكرار نفس الطالب في الحصة.",
  "Lesson subject, level, date, start time, and end time are required": "بيانات الحصة الأساسية مطلوبة.",
  "Invalid private lesson format": "نوع الحصة غير صالح.",
  "Invalid lesson time range": "وقت النهاية يجب أن يكون بعد وقت البداية.",
  "Amount paid cannot exceed lesson price": "لا يمكن أن يتجاوز المدفوع سعر الحصة.",
  "Completed private lessons cannot be edited; create an adjustment instead": "لا يمكن تعديل حصة مكتملة؛ استخدم إجراء تصحيح مالي.",
  "Invalid student list": "قائمة الطلاب غير صالحة.",
  "Completed private lessons cannot be cancelled": "لا يمكن إلغاء حصة مكتملة.",
  "Cancellation reason is required": "سبب الإلغاء مطلوب.",
  "New date and time are required": "التاريخ والتوقيت الجديدان مطلوبان.",
  "Invalid postponed time range": "وقت التأجيل غير صالح.",
  "Valid lesson and replacement teacher are required": "الحصة والأستاذ البديل مطلوبان.",
  "Replacement reason is required": "سبب تغيير الأستاذ مطلوب.",
  "Series start date is required": "تاريخ بداية السلسلة مطلوب.",
  "Valid price and effective date are required": "السعر وتاريخ السريان مطلوبان.",
  "Invalid compensation id": "معرّف التعويض غير صالح.",
  "Teacher compensation not found": "تعويض الأستاذ غير موجود.",
  "Note is required": "الملاحظة مطلوبة.",
  "Valid lesson and student are required": "الحصة والطالب مطلوبان.",
  "Invalid payment amount": "مبلغ الدفع غير صالح.",
  "Payment cannot exceed remaining lesson balance": "لا يمكن أن يتجاوز الدفع الرصيد المتبقي للحصة.",
  "Kindergarten registration not found": "تسجيل الروضة غير موجود.",
  "Active teacher is required": "المربية غير متاحة أو أن حالتها لا تسمح بإسناد الطفل إليها.",
  "Invalid subscription type": "نوع الاشتراك مطلوب.",
  "File fee paid cannot exceed registration fee": "لا يمكن أن يتجاوز دفع الملف رسوم الملف.",
  "Subscription amount paid cannot exceed price": "لا يمكن أن يتجاوز دفع الاشتراك مبلغ الاشتراك.",
  "Child, guardian phone, group, schedule, and billing period are required": "اسم الطفل وهاتف الولي والفوج وبرنامج الحضور وفترة الاشتراك مطلوبة.",
  "Invalid payment type": "نوع الدفع غير صالح.",
  "Registration is not weekly": "هذا التسجيل ليس أسبوعيا.",
  "Registration is not monthly": "هذا التسجيل ليس شهريا.",
  "Payment cannot exceed remaining balance": "لا يمكن أن يتجاوز الدفع الرصيد المتبقي.",
  "Subscription change reason is required": "سبب تغيير الاشتراك مطلوب.",
  "Subscription price is required": "مبلغ الاشتراك غير صالح.",
  "Billing period is required": "فترة الاشتراك غير صالحة.",
  "Duplicate billing period is not allowed": "توجد فاتورة لنفس الطفل ونفس فترة الاشتراك.",
  "Teacher already has a kindergarten schedule at this time": "المربية لديها تسجيل آخر في هذا التوقيت.",
  "Child already has a kindergarten schedule at this time": "الطفل لديه تسجيل آخر في هذا التوقيت.",
  "Could not generate receipt number": "تعذر توليد رقم وصل فريد.",
};

export function arabicError(error: unknown, fallback = "حدث خطأ") {
  const message = error instanceof Error ? error.message : String(error || "");
  return ERROR_MAP[message] || (/[A-Za-z]/.test(message) ? fallback : message || fallback);
}
